server {
  resolver 127.0.0.11 valid=10s ipv6=off;
  set $api_upstream http://api:8000;
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-hashes' 'sha256-bUSk12rXwnfV2clICEDIFiVabvleE/VIiel/TcSK2bg=' 'sha256-SSB8194xmAE2DBXviHSYCOsxcTktW9X1kLUvwj9vOmA=' 'sha256-d9Gmf3diWTarDIE/UUhDuSF1ksINhxgAI6HVVSaikHs=' 'sha256-xjHA3mtUY+mSl2NHqRCJiS0l5R6njKfphiLrDAsQGj8=' 'sha256-lBdBpj7Qn1iknVjcoMOFNCUCZJE4tGpo6L5KiObHSJ4=' 'sha256-MJYyRHTEuN9oeJ2CNpYeVA9evBuc8F8Vr0OpjAW/sxg=' 'sha256-l1DjPrgQGviXvrP2iqdl5JKbR6QNbU3uMnF2Ca9LbWs=' 'sha256-qXVoNfp1YBtxZVRuMYykFMpKMnM6MFWCO6aB6gDzkOQ=' 'sha256-XRNY35QhPIi24bv/UZJPgS03kowpDoVCkA8TgS4O/Nc=' 'sha256-C8n9mjPkF5r1OsN2g/TjK2tQah57fm68856UFp/6Vfk=' 'sha256-sOLUTTw+ymupXNP8I7N6HLCzLWsOv1fjTnENsrhE/sA=' 'sha256-Qx/2180l8xP1Yth0WNk2ozsJgdMT6B5McZL72EgnrSs=' 'sha256-FFhj7HER4LWbDu+wEocmxZx7yrtwo+9AIUfrXWJ5JiQ=' 'sha256-fVbtlsNhlQ7efNpHifI52o+hr3Kg/wP03M8ReG62BRY=' 'sha256-D35EvqhcGkxRcAS8L9hbBwtTz7jV4HtansqD/yho1hQ=' 'sha256-CO0ctbRa/8LI2Jo6GzwaDy9kqGjC1Mn8FYnM4JF4HuU=' 'sha256-6k5fSMAFnsV8YPGD9Q513DL2yT/nWwnU20pbXoTVLcw='; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://*.basemaps.cartocdn.com; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'" always;
  add_header X-Content-Type-Options "nosniff" always;
  add_header Referrer-Policy "no-referrer" always;
  add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api {
    proxy_pass $api_upstream;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /ws {
    proxy_pass $api_upstream;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
